name: Auto-Merge PR

on:
  pull_request_target:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
