name: Publish Package

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  github:
    name: GitHub Package Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - name: Set Registry
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
          echo "registry=https://npm.pkg.github.com/alexlafroscia" >> .npmrc
      - name: Publish
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
